In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("IMDB Dataset.csv")

In [3]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.shape

(50000, 2)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
review       50000 non-null object
sentiment    50000 non-null object
dtypes: object(2)
memory usage: 781.3+ KB


In [6]:
df['sentiment'].head()

0    positive
1    positive
2    positive
3    negative
4    positive
Name: sentiment, dtype: object

In [7]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [8]:
# re -> regular expressions
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

sw = stopwords.words('english')
print(sw)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ROHIT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [9]:
len(sw)

179

In [10]:
#  cleaning of your data

def clean_text(sample):
  sample = sample.lower()
  sample = sample.replace("<br /><br />", "")
  sample = re.sub("[^a-z]+", " ", sample)
  sample = sample.split(" ")
  
  sample = [word for word in sample if word not in sw ] # list comprehension

  sample = " ".join(sample)

  return sample

In [11]:
clean_text(df['review'][1])

'wonderful little production filming technique unassuming old time bbc fashion gives comforting sometimes discomforting sense realism entire piece actors extremely well chosen michael sheen got polari voices pat truly see seamless editing guided references williams diary entries well worth watching terrificly written performed piece masterful production one great master comedy life realism really comes home little things fantasy guard rather use traditional dream techniques remains solid disappears plays knowledge senses particularly scenes concerning orton halliwell sets particularly flat halliwell murals decorating every surface terribly well done '

In [12]:
df['review'] = df['review'].apply(clean_text)

In [13]:
df.head()

review sentiment
0  one reviewers mentioned watching oz episode ho...  positive
1  wonderful little production filming technique ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically family little boy jake thinks zombie...  negative
4  petter mattei love time money visually stunnin...  positive

In [14]:
# X -> input
# y -> output


In [15]:
# another library for converting pos/neg to 1/0
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# learning the mapping pos :1 , neg :0
#le.fit(X)

In [16]:
df['sentiment_n']=le.fit_transform(df['sentiment'])

In [17]:
df.head()

review sentiment  sentiment_n
0  one reviewers mentioned watching oz episode ho...  positive            1
1  wonderful little production filming technique ...  positive            1
2  thought wonderful way spend time hot summer we...  positive            1
3  basically family little boy jake thinks zombie...  negative            0
4  petter mattei love time money visually stunnin...  positive            1

In [18]:
df1=df.drop('sentiment',axis='columns')

In [19]:
df1.head()

review  sentiment_n
0  one reviewers mentioned watching oz episode ho...            1
1  wonderful little production filming technique ...            1
2  thought wonderful way spend time hot summer we...            1
3  basically family little boy jake thinks zombie...            0
4  petter mattei love time money visually stunnin...            1

In [39]:
X = df1['review'].values
y = df1['sentiment_n'].values

In [21]:
# Bag of Word Model
# it convert sentences into numbers

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 20000)

In [22]:
X= cv.fit_transform(df1['review']).toarray()

In [23]:
X.shape

(50000, 20000)

In [24]:
X[0].max()

6

In [25]:
y.shape

(50000,)

In [26]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [28]:
X_train.shape

(40000, 20000)

# Model Training

In [29]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
mnb = MultinomialNB()

In [30]:
# training part
mnb.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [31]:
y_pred=mnb.predict(X_test)

In [32]:
y_pred

array([0, 1, 0, ..., 0, 1, 1])

In [33]:
accuracy_score(y_test,y_pred)

0.8557

# Predict for One sentence

In [34]:
my_review =  " Like expected,superb action flick! Any of the Rock or Statham movies never disappoint! For a die hard traditional action fans-a must see!"

In [35]:
# my_review = " the movie was too boring a waste of time , pathetic storyline "

In [36]:
my_review = clean_text(my_review)

In [37]:
my_review = cv.transform([my_review])

In [38]:
mnb.predict(my_review)

array([1])